#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Action Tag Release

on:
  workflow_call:
    inputs:
      user:
        description: 'Optional GitHub username that is associated with the GitHub Personal Access Token (PAT)'
        type: string
        required: false
        default: ''
    secrets:
      access-token:
        description: 'GitHub Personal Access Token (PAT) if the default branch is protected and needs a specific access token to push tags to the branch'
        required: false

jobs:
  tagrelease:
    name: Action Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.event.secrets.access-token || github.token }}
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest-version
      - name: Retrieve version
        run: |
          VERSION=${{ steps.latest-version.outputs.tag }}
          MAJOR=${VERSION%%.*}
          MINOR=${VERSION%.*}
          
          git config user.name "${{ github.event.inputs.user || github.actor }}"
          git config user.email "${{ github.event.inputs.user || github.actor }}@users.noreply.github.com"
          
          git tag -a -f "${MAJOR}" -m "${MAJOR}"
          git tag -a -f "${MINOR}" -m "${MINOR}"
          git push -f --tags
