#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Action Tag Release

on:
  workflow_call:
    inputs:
      user:
        description: 'Optional GitHub username that is associated with the GitHub Personal Access Token (PAT)'
        type: string
        required: false
        default: ''
    secrets:
      access-token:
        description: 'GitHub Personal Access Token (PAT) if the default branch is protected and needs a specific access token to push tags to the branch'
        required: false

jobs:
  tagrelease:
    name: Action Tag Release
    uses: StanfordBDHG/.github/.github/workflows/action-release-tag.yml@v2
    secrets:
      access-token: ${{ secrets.access-token }}
    with:
      user: ${{ inputs.user }}
