#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Action Tag Release

on:
  workflow_call:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  tagrelease:
    name: Action Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest-version
      - name: Retrieve version
        run: |
          VERSION=${{ steps.latest-version.outputs.tag }}
          MAJOR=${VERSION%%.*}
          MINOR=${VERSION%.*}

          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git tag -a "${MAJOR}" -m "${MAJOR}"
          git tag -a "${MINOR}" -m "${MINOR}"
          git push -f --tags
