name: Diagnose Breaking Changes

on:
  workflow_call:
    inputs:
      branch:
        description: 'The name of the branch to compare against'
        required: true
        type: string

jobs:
  diagnose:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run diagnose-api-breaking-changes
        run: swift package diagnose-api-breaking-changes ${{ inputs['branch'] }}
