#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Create and upload coverage report

on:
  workflow_call:
    inputs:
      coveragereports:
        description: 'A string containing all names of the .xcresult files that are downloaded from the artifacts of previous jobs separated by a space character.'
        required: true
        type: string
    secrets:
      token:
        description: 'The CodeCov token used for private repositories'
        required: false

jobs:
  create-and-upload-coverage-report:
    name: Create and upload coverage report
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    secrets:
      token: ${{ secrets.token }}
    with:
      coveragereports: ${{ inputs.coveragereports }}
