#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releasetag:
    name: Tag Release
    uses: StanfordBDHG/.github/.github/workflows/action-release-tag.yml@v2
    permissions:
      contents: write
    with:
      user: PaulsAutomationBot
