#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: SwiftLint

on:
  workflow_call:
    inputs:
      version:
        description: Swiftlint version
        type: string
        default: latest
        required: false


jobs:
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
    with:
      version: ${{ inputs.version }}
