#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: SwiftLint

on:
  workflow_call:
    inputs:
      path:
        description: 'The path where the project is located. Defaults to $GITHUB_WORKSPACE'
        required: false
        type: string
        default: '.'

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SwiftLint
        uses: sinoru/actions-swiftlint@v6
        with:
          swiftlint-version: '0.50.0'
          swiftlint-args: --strict
